import { defineTextCategory } from "../types";

export const dinnerTexts = defineTextCategory({
  title: "Dinner page and signup",
  description:
    "A single dinner's page, including the signup form around the fields you set up per dinner.",
  scope: "root",
  entries: {
    backLink: {
      group: "Dinner page",
      label: "Link back to all dinners",
      kind: "line",
      default: "all dinners",
    },
    menuHeading: {
      group: "Dinner page",
      label: "Menu section",
      help: "The fold-out section with the dinner's menu.",
      kind: "line",
      default: "menu",
    },
    donationHeading: {
      group: "Dinner page",
      label: "Donation section",
      help: "The fold-out section with the dinner's donation text.",
      kind: "line",
      default: "donation",
    },

    locationLabel: {
      group: "Dinner facts",
      label: "Location (screen readers)",
      help: "Not visible; read out before the address. The facts also show on the next dinner's card on the dinners page.",
      kind: "line",
      default: "location",
    },
    priceLabel: {
      group: "Dinner facts",
      label: "Price (screen readers)",
      help: "Not visible; read out before the price.",
      kind: "line",
      default: "price",
    },
    price: {
      group: "Dinner facts",
      label: "Price",
      help: "{price} is the dinner's price.",
      kind: "line",
      default: "{price} chf",
      placeholders: ["price"],
    },
    seatsOne: {
      group: "Dinner facts",
      label: "Seats, one seat",
      help: "{count} is the number of seats.",
      kind: "line",
      default: "{count} seat",
      placeholders: ["count"],
    },
    seatsMany: {
      group: "Dinner facts",
      label: "Seats, several seats",
      help: "{count} is the number of seats.",
      kind: "line",
      default: "{count} seats",
      placeholders: ["count"],
    },
    discountsButton: {
      group: "Dinner facts",
      label: "Discounts button",
      help: "Next to the price; opens the dinner's discounts.",
      kind: "line",
      default: "discounts",
    },
    noDiscounts: {
      group: "Dinner facts",
      label: "Text when there are no discounts",
      help: "Shown when the discounts button is opened on a dinner without discounts.",
      kind: "line",
      default: "no discounts currently available",
    },

    signupHeading: {
      group: "Signup",
      label: "Heading above the form",
      kind: "line",
      default: "reserve your seat",
    },
    listFieldLimit: {
      group: "Signup",
      label: "Limit next to a repeating field",
      help: "Shown next to fields guests can add several times, such as friends. {count} is the most they can add.",
      kind: "line",
      default: "up to {count}",
      placeholders: ["count"],
    },
    privacyConsent: {
      group: "Signup",
      label: "Privacy checkbox",
      help: "The box guests tick under the form. {link} is where the link to the privacy policy goes.",
      kind: "line",
      default: "i agree to the {link}",
      placeholders: ["link"],
    },
    privacyConsentLink: {
      group: "Signup",
      label: "Privacy checkbox: link text",
      kind: "line",
      default: "privacy policy",
    },
    signupButton: {
      group: "Signup",
      label: "Signup button",
      kind: "line",
      default: "join this dinner",
    },
    signupNote: {
      group: "Signup",
      label: "Note under the button",
      kind: "line",
      default: "we'll email you to confirm if a seat is yours.",
    },
    signupSuccessTitle: {
      group: "Signup",
      label: "Confirmation after signing up: title",
      help: "Pops up on the dinners page once someone has signed up.",
      kind: "line",
      default: "Signup complete",
    },
    signupSuccessBody: {
      group: "Signup",
      label: "Confirmation after signing up: text",
      kind: "line",
      default: "We'll contact you if you were able to get a spot on the event.",
    },

    metaTitle: {
      group: "Search engines and link previews",
      label: "Browser tab title",
      help: "{title} is the dinner's title.",
      kind: "line",
      default: "Dinner: {title}",
      placeholders: ["title"],
    },
    metaTitleFallback: {
      group: "Search engines and link previews",
      label: "Browser tab title when the dinner can't be found",
      kind: "line",
      default: "Dinner",
    },
  },
});
